---
title: "Final Outline 2"
format: pdf
editor: visual
---

# Load Libraries

```{r}
library(Lahman)
library(tidyverse)
library(broom)
library(modelsummary)
library(fixest)
library(quantmod)
```

# Load Datasets & Filter

```{r}
Batting <- Lahman::Batting
Appearances <- Lahman::Appearances

#DF of position players
PositionAppearances <- Appearances %>% 
  #Gross filter to find position players
  #Arbitrarily selected 5 because that filtered out a lot of PO's who came in a couple times
  filter(G_c >= 5 | G_1b >= 5 | G_2b >= 5 | G_3b >= 5 | G_ss >= 5 | G_lf >= 5 | G_cf >= 5 | G_rf >= 5 | G_of >= 5 | G_dh >= 5) %>%
  arrange(desc(G_p))

#Filter batting data by position players
PositionBatting <- Batting %>% 
  filter(playerID %in% PositionAppearances$playerID) %>% 
  #Only grab players who played in or after 1985
  #Omit 2020 because it creates 30 outliers with only 60 games played
  filter(yearID >= 1985 & yearID != 2020) %>% 
  #Isolate singles as X1B to keep naming convention
  mutate(X1B = H - X2B - X3B - HR, .after = H) %>% 
  #Introduce "catch-all" term for "free base"
  mutate(OB = BB + HBP + IBB, .after = HBP)
```

```{r}
PositionBatting$yearID <- as.factor(PositionBatting$yearID)
PositionBatting
```

```{r}
PositionAppearances$yearID <- as.factor(PositionAppearances$yearID)
PositionAppearances
```

```{r}
Teams <- Lahman::Teams

Teams1985 <- Teams %>% 
  #Omit 2020 because it creates 30 outliers with only 60 games played
  filter(yearID >= 1985 & yearID != 2020) %>% 
  mutate(X1B = H - X2B - X3B - HR, .after = H) %>% 
  mutate(OB = BB + HBP, .after = HBP)
```

# Create Models

Fixed Effects for Linear Weights

```{r}
TeamLW <- lm(data = Teams1985, R ~ X1B + X2B + X3B + HR + OB + SB + SF + yearID + teamID)
summary(TeamLW)
```

```{r}
feols(R ~ X1B + X2B + X3B + HR + OB + SB + SF | yearID + teamID, data = Teams1985)
```

# Salary

```{r}
Salaries <- Lahman::Salaries
Salaries
```

```{r}
getSymbols("CPIAUCSL", src='FRED')
avg.cpi <- apply.yearly(CPIAUCSL, mean)
cf <- avg.cpi/as.numeric(avg.cpi['2021'])
dat <- merge(Salaries, cf, all=FALSE)
newdat <- dat %>% 
  mutate(INFadj = salary / CPIAUCSL)
```

```{r}
avgSal <- Salaries %>% 
  group_by(yearID) %>% 
  summarize(avg_salary = mean(salary))

avgSal$yearID <- ISOdate(avgSal$yearID, 12, 1)
avgSal$yearID <- as.Date(avgSal$yearID)

cf2 <- cf %>% 
  fortify.zoo() %>% 
  as.tibble()

cf2 <- cf2 %>% 
  rename(yearID = Index)

avgSal <- inner_join(avgSal, cf2)

avgSal <- avgSal %>% 
  mutate(real_wage = avg_salary*CPIAUCSL)
```

```{r}
ggplot(data = avgSal)+
  aes(x=yearID,
      y=real_wage)+
  geom_count()
```
